#!/bin/bash

# Run Script

echo "Script running"

source env/bin/activate

export FLASK_APP=server.py
export FLASK_ENV=development
export FLASK_RUN_PORT=6900
flask run --host=0.0.0.0 &
sudo python3 main.py &

